export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAILURE = "SIGNIN_USER_FAILURE";
export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const EMAIL_VALID_REQUEST = "EMAIL_VALID_REQUEST";
export const EMAIL_VALID_SUCCESS = "EMAIL_VALID_SUCCESS";
export const EMAIL_VALID_FAILURE = "EMAIL_VALID_FAILURE";
export const OTP_VALID_REQUEST = "OTP_VALID_REQUEST";
export const OTP_VALID_SUCCESS = "OTP_VALID_SUCCESS";
export const OTP_VALID_FAILURE = "OTP_VALID_FAILURE";
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

// Landing Page
export const OPEN_LOGIN = "OPEN_LOGIN";
export const OPEN_REGISTER = "OPEN_REGISTER";
export const OPEN_FORGET_PASSWORD = "OPEN_FORGET_PASSWORD";
export const CLOSE_FORGET_PASSWORD = "CLOSE_FORGET_PASSWORD";
export const INCREMENT_PHASE = "INCREMENT_PHASE";
